// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhllEDP9vZy8mq7-Mkyh-j7eFrAsILZUM',
    appId: '1:881251314312:web:fc8135bfd36731f123cd3d',
    messagingSenderId: '881251314312',
    projectId: 'muncitor-pe-loc',
    authDomain: 'muncitor-pe-loc.firebaseapp.com',
    storageBucket: 'muncitor-pe-loc.firebasestorage.app',
    measurementId: 'G-EXM07TT4FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kVDxftR2ZoBRVeVBqIA0_Jv8OxsWcJM',
    appId: '1:881251314312:android:cb945acc07fd5cc423cd3d',
    messagingSenderId: '881251314312',
    projectId: 'muncitor-pe-loc',
    storageBucket: 'muncitor-pe-loc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJGN-4CtAvPwf87J1o4v5rCEutEwcpo4',
    appId: '1:881251314312:ios:bdab344db26536cb23cd3d',
    messagingSenderId: '881251314312',
    projectId: 'muncitor-pe-loc',
    storageBucket: 'muncitor-pe-loc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxJGN-4CtAvPwf87J1o4v5rCEutEwcpo4',
    appId: '1:881251314312:ios:bdab344db26536cb23cd3d',
    messagingSenderId: '881251314312',
    projectId: 'muncitor-pe-loc',
    storageBucket: 'muncitor-pe-loc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhllEDP9vZy8mq7-Mkyh-j7eFrAsILZUM',
    appId: '1:881251314312:web:176daaed7c37eb0f23cd3d',
    messagingSenderId: '881251314312',
    projectId: 'muncitor-pe-loc',
    authDomain: 'muncitor-pe-loc.firebaseapp.com',
    storageBucket: 'muncitor-pe-loc.firebasestorage.app',
    measurementId: 'G-CRJHPMW2EK',
  );
}
